name: piplup
description: This is my personal OS image.
base-image: ghcr.io/ublue-os/aurora
image-version: 39 # latest is also supported if you want new updates ASAP

modules:
  - type: files
    files:
      - usr: /usr

  - from-file: rpm-ostree.yml
  - from-file: user-flatpaks.yml
  - from-file: system-flatpaks.yml

  - type: signing
