name: piplup
description: This is my personal OS image.
base-image: ghcr.io/ublue-os/aurora
image-version: 39 # latest is also supported if you want new updates ASAP

modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/nickavem/mozilla-vpn-client/repo/fedora-%OS_VERSION%/mozilla-vpn-client-%OS_VERSION%
    install:
      - mozillavpn
    remove:
      - firewalld
      - firewalld-filesystem
      - ublue*
      - qemu*
  # - from-file: rpm-ostree.yml

  - type: default-flatpaks
    notify: true
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (User)"
      install:
        - org.mozilla.firefox
  # - from-file: user-flatpaks.yml

  - type: signing
